/* autogenerated by Processing revision 1308 on 2026-05-06 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;
import controlP5.*;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Interactive extends PApplet {

//================================================================



//================================================================

int qtyInstruments = 3;

//----------------------------------------------------------------

PShader noiseLayer;
PShader feedbackLayer;
PGraphics pg;

//----------------------------------------------------------------
// switches for processing
boolean sortShader = false;
boolean shiftShader = false;
boolean shiftSort = false;
boolean sortFeedback = false;
boolean reverseSort= false;
boolean devMode = false;
boolean preProcess = false;
boolean postProcess = false;

boolean cloudFlag = false;

//----------------------------------------------------------------
// value for pixelsorting

int sortMode = 0;

// GLOBALS functions like updateThresholds, thresholdSort and evalPixel
int thMin = 0;
int thMax = 0;
float thCenter = 0.0f;
float thWidth = 0.0f;

//----------------------------------------------------------------

InputAnalyzer hang;
InputAnalyzer bodhran;
InputAnalyzer kalimba;

float hangOffset = 0.0f;
float kalimbaOffset = 0.0f;
float bodhranOffset = 0.0f;

float hangAmplitude = 0.0f;
float kalimbaAmplitude = 0.0f;
float bodhranAmplitude = 0.0f;

//----------------------------------------------------------------
// Color controls

float blend = 0.0f;
float rate = 0.001f;
int blendStart = 0;
int blendDuration = 1200;

//----------------------------------------------------------------

float[] gain = new float[qtyInstruments];
PVector[] offset = new PVector[qtyInstruments];
float noiseZoomFactor;
float feedbackZoomFactor;
float alphaCenter = 0.0f;
float alphaWidth = 0.0f;

float feedbackAlpha = 0.0f;
float darkenAmount = 0.0f;
float brightenAmount = 0.0f;
float fbmWarp = 0.0f;

// Wall dimensions: 361" x 144" - projector location? distance back?
// Projector Aspect Ratio: 16:9
// Distance between projection wall and rear wall: 17' 5" (209")
// Max Projection Dimensions (16:9): 256" x 144" (~294" diagonal)

//----------------------------------------------------------------

ArrayList<Palette> palettes;

Palette activePaletteA;
Palette activePaletteB;
Palette mixedPalette;

//----------------------------------------------------------------

ControlFrame cf;

//================================================================

public void setup() {
  /* pixelDensity commented out by preprocessor */;
  /* size commented out by preprocessor */;
  //size(1280, 720, P2D);
  frameRate(30);
  noiseDetail(7, 0.5f);
  noStroke();

  // instantiate the ControlFrame
  cf = new ControlFrame(this, 400, 800);

  palettes = loadPalettes();
  activePaletteA = palettes.get(PApplet.parseInt(random(palettes.size())));
  activePaletteA.randomizePastels();
  activePaletteB = palettes.get(PApplet.parseInt(random(palettes.size())));
  activePaletteB.randomizePastels();

  // Load and compile noise shader
  noiseLayer = loadShader("noise.frag");
  // We only have to set resolution once
  noiseLayer.set("u_resolution", PApplet.parseFloat(width), PApplet.parseFloat(height));

  feedbackLayer = loadShader("feedback.frag");
  //feedbackLayer.set("u_resolution", float(width), float(height));

  // Create an off-screen rendering context
  pg = createGraphics(width, height, P2D);

  // Initialize the sound device
  try {
    //Sound s = new Sound(this);
    String device = "Scarlett 18i8 USB";
    processing.sound.Sound.inputDevice(device);
  }
  catch(Exception e) {
    print("While initializing Sound Object: " + e);
  }

  // create analyzers for each of the instruments
  bodhran = new InputAnalyzer(this, 0, 2048, 1024);
  hang = new InputAnalyzer(this, 1, 2048, 1024);
  kalimba = new InputAnalyzer(this, 2, 2048, 1024);

  //used to create unique starting conditions for the pastel noise layers
  offset[0] = new PVector(
    random(-2, 2),
    random(-2, 2),
    bodhranOffset
    );
  offset[1] = new PVector(
    random(-2, 2),
    random(-2, 2),
    hangOffset
    );
  offset[2] = new PVector(
    random(-2, 2),
    random(-2, 2),
    kalimbaOffset
    );

  blendStart = frameCount;
}

//================================================================

public void draw() {

  //read analyzers

  bodhranAmplitude = bodhran.getAmplitude();
  bodhranOffset += bodhranAmplitude;

  hangAmplitude = hang.getAmplitude();
  hangOffset += hangAmplitude;

  kalimbaAmplitude = kalimba.getAmplitude();
  kalimbaOffset += kalimbaAmplitude;

  //feedbackZoomFactor = 1.0 - noise(1, (bodhranAmplitude+hangAmplitude+kalimbaAmplitude)/3);
  //noiseZoomFactor = 5;

  gain[0] = 2.0f * bodhranAmplitude;
  gain[1] = 2.0f * hangAmplitude;
  gain[2] = 2.0f * kalimbaAmplitude;

  offset[0].z = bodhranOffset;
  offset[1].z = hangOffset;
  offset[2].z = kalimbaOffset;

  // Set uniforms

  if (pg != null) {

    // if (sortFeedback) pixelsort(pg, reverseFeedbackSort);
    pg.beginDraw();
    pg.noStroke();

    background(getBGColor());

    feedbackLayer.set("u_alpha", feedbackAlpha);
    feedbackLayer.set("u_feedbackZoom", feedbackZoomFactor);
    feedbackLayer.set("u_centerX", mouseX/PApplet.parseFloat(width));
    feedbackLayer.set("u_centerY", 1 - mouseY/PApplet.parseFloat(height));
    pg.shader(feedbackLayer);
    pg.image(pg, 0, 0);

    for (int i = 0; i < qtyInstruments; i++) {
      setShaderParams(i);
      pg.shader(noiseLayer);
      pg.rect(0, 0, pg.width, pg.height);
      pg.resetShader(); // necessary to maintain layer independence
    }

    //draw crosshairs
    //pg.stroke(255);
    //pg.line(0, mouseY, width, mouseY);
    //pg.line(mouseX, 0, mouseX, height);

    pg.endDraw();

    if (preProcess) process(pg);

    image(pg, 0, 0);
  }

  if (postProcess) process();

  if (devMode) showInfo();

  updateBlend();
}

//================================================================

public void setShaderParams(int i) {
  float[] pastel = getPaletteColor(i);
  noiseLayer.set("u_color", pastel[0], pastel[1], pastel[2]);
  noiseLayer.set("u_time", millis() * 0.0001f);
  noiseLayer.set("u_offset", offset[i]);
  noiseLayer.set("u_zoom", noiseZoomFactor);
  noiseLayer.set("u_center", alphaCenter);
  noiseLayer.set("u_width", alphaWidth);
  noiseLayer.set("u_darken", darkenAmount);
  noiseLayer.set("u_brighten", brightenAmount);
  noiseLayer.set("u_warp", fbmWarp);
}

//================================================================
// Diagnostics Display

public void showInfo() {
  fill(255);
  text("bodhran: " + gain[0], 100, 50);
  text("hang pan: " + gain[1], 100, 80);
  text("kalimba: " + gain[2], 100, 110);
  text("frameCount: " + frameCount, 100, 140);
  text("blendStart: " + blendStart, 100, 170);
  text("blendDuration: " + blendDuration, 100, 200);
  text("blend: " + blend, 100, 230);
  text("noiseZoomFactor: " + noiseZoomFactor, 100, 260);

  text("bodhranOffset: " + bodhranOffset, 250, 50);
  text("hangOffset: " + hangOffset, 250, 80);
  text("kalimbaOffset: " + kalimbaOffset, 250, 110);

  text("minThreshold: " + thMin, 250, 140);
  text("maxThreshold: " + thMax, 250, 170);

  noStroke();

  fill(getBGColor());
  square(20, 50, 30);
  for (int i = 0; i < qtyInstruments; i++) {
    float[] pastel = getPaletteColor(i);
    fill(
      round(pastel[0]*255),
      round(pastel[1]*255),
      round(pastel[2]*255)
      );
    square(20, 80+(i*30), 30);
  }
}

//================================================================
// Pixel Sorting Related Functions

public void updateThresholds() {
  thMin = round(255 * thCenter * (1 - thWidth));
  thMax = round(255 * (thCenter * (1 - thWidth) + thWidth));
}

//----------------------------------------------------------------

public void process(PGraphics _pg) {
  if (sortShader ==false &&
    shiftShader == false &&
    sortFeedback == false &&
    reverseSort == false ) return;

  _pg.beginDraw();
  _pg.loadPixels();
  processPixels(_pg.pixels, _pg.height, _pg.width);
  _pg.updatePixels();
  _pg.endDraw();
}

//----------------------------------------------------------------

public void process() {
  loadPixels();
  processPixels(pixels, height, width);
  updatePixels();
}

//----------------------------------------------------------------

public void processPixels(int[] _pixels, int _height, int _width) {
  int[] column = new int[_height];

  for (int x = 0; x < _width; x++) {
    for (int y = 0; y < _height; y++) {
      column[y] = _pixels[y * _width + x];
    }

    if (sortShader) column = thresholdSort(column, sortMode);

    if (shiftShader) {
      int amount = round(((bodhranAmplitude+hangAmplitude+kalimbaAmplitude)/3.0f) * column.length * (noise(
        0.01f * x,
        _height * frameCount * 0.0001f)-0.5f
        ));
      column = shift(column, amount);
    }

    for (int y = 0; y < _height; y++) {
      _pixels[y * _width + x] = column[y];
    }
  }
}

//----------------------------------------------------------------

// different ways in which the threshold for max and min can be used to mask pixels to be sorted
public boolean evalPixel(float _value, int _mode, boolean _flag) {
  switch(_mode) {
  case 0: // pixel values below center
    return _flag ? _value >= round(255 * thCenter) : _value < round(255 * thCenter);
  case 1: // start capture pixels below min, stop above max
    return _flag ? _value >= thMax : _value < thMin;
  case 2: // pixel values above min
    return _flag ? _value <= round(255 * thCenter): _value > round(255 * thCenter);
  case 3: // start capture pixels above max, stop below min
    return _flag ? _value <= thMin : _value > thMax;
  case 4: // start capture pixels below max, stop capture below min
    return _flag ? _value <= thMin  || _value >= thMax : _value < thMax && _value > thMin;
  case 5:  // start capture pixels below max, stop capture below min
    return _flag ? _value >= thMin  && _value <= thMax : _value > thMax || _value < thMin;
  }
  return false;
}

//----------------------------------------------------------------

// pixelsorting on the main rendering chain
public int[] thresholdSort(int[] pixelArray, int mode) {
  boolean segmentFlag = false;
  int start = 0;
  int end = 0;
  float value;
  for (int i = 0; i < pixelArray.length; i++) {
    value = brightness(pixelArray[i]);

    if (!segmentFlag && evalPixel(value, mode, segmentFlag)) {
      start = i;
      segmentFlag = true;
    } else if (segmentFlag && (evalPixel(value, mode, segmentFlag) || i == pixelArray.length - 1)) {
      end = i;
      segmentFlag = false;
      int[] chunk = new int[end-start];
      for (int j = 0; j < end-start; j++) {
        chunk[j] = pixelArray[start+j];
      }
      chunk = sort(chunk);
      if (reverseSort) chunk = reverse(chunk);
      if (shiftSort) {
        int amount = round(chunk.length * noise(
          0.1f * i,
          frameCount * 0.0001f));
        chunk = shift(chunk, amount);
      }
      for (int j = 0; j < end-start; j++) {
        pixelArray[start+j] = chunk[j];
      }
    }
  }

  return pixelArray;
}

//----------------------------------------------------------------

public int[] shift(int[] array, int amount) {
  int[] shifted = new int[array.length];
  int j = 0;
  for (int i = 0; i < shifted.length; i++) {
    j = (i + amount) % array.length;
    shifted[i] = array[j < 0 ? j + array.length : j];
  }
  return shifted;
}

//================================================================
// Shaper functions

public float doubleExponentialSigmoid (float x, float a) {

  float epsilon = 0.00001f;
  float min_param_a = 0.0f + epsilon;
  float max_param_a = 1.0f - epsilon;
  a = constrain(a, min_param_a, max_param_a);
  a = 1.0f - a; // for sensible results

  float y = 0.0f;

  if (x <= 0.5f) {
    y = (pow(2.0f * x, 1.0f / a)) / 2.0f;
  } else {
    y = 1.0f - (pow(2.0f * (1.0f - x), 1.0f / a)) / 2.0f;
  }
  return y;
}

//================================================================
// Color Management Functions

public void updateBlend() {
  if (frameCount - blendStart > blendDuration) {
    activePaletteA = activePaletteB.copy();
    activePaletteB = palettes.get(PApplet.parseInt(random(palettes.size())));
    activePaletteB.randomizePastels();
    blendStart = frameCount;
  }

  blend = doubleExponentialSigmoid(
    (frameCount - blendStart) / PApplet.parseFloat(blendDuration),
    0.9f);
}

//----------------------------------------------------------------

public int getBGColor() {
  return color(
    round(255*lerp(activePaletteA.background[0], activePaletteB.background[0], blend)),
    round(255*lerp(activePaletteA.background[1], activePaletteB.background[1], blend)),
    round(255*lerp(activePaletteA.background[2], activePaletteB.background[2], blend))
    );
}

//----------------------------------------------------------------

public float[] getPaletteColor(int index) {
  return new float[]{
    lerp(activePaletteA.pastels[index][0], activePaletteB.pastels[index][0], blend),
    lerp(activePaletteA.pastels[index][1], activePaletteB.pastels[index][1], blend),
    lerp(activePaletteA.pastels[index][2], activePaletteB.pastels[index][2], blend)
  };
}
//================================================================
// Import ControlP5 library



//----------------------------------------------------------------
int margin_x = 10;
int margin_y = 10;
int unit_w = 20;
int unit_h = 20;
int buffer_w = 10;
int buffer_h = 10;

public int grid_x(int steps) {
  return margin_x + steps * (unit_w + buffer_w);
}

public int grid_y(int steps) {
  return margin_y + steps * (unit_w + buffer_w);
}

public int size_w(int units) {
  units = max(units, 1);
  return (unit_w * units) + (buffer_w * (units - 1));
};

public int size_h(int units) {
  units = max(units, 1);
  return (unit_h * units) + (buffer_h * (units - 1));
};

//----------------------------------------------------------------

RadioButton sortModeRadio;

Numberbox sort_min;
Numberbox sort_max;

controlP5.Label label;

//================================================================
// ControlFrame for controls in separate window.
// Connection between gui elements and variables in the parent applet are
// made via the plugTo(<parent>, <name>) method.

class ControlFrame extends PApplet {
  int w, h;
  String name;
  PApplet parent;
  ControlP5 cp5;

  public ControlFrame(PApplet _parent, int _w, int _h) {
    super();
    parent = _parent;
    w=_w;
    h=_h;
    PApplet.runSketch(new String[]{this.getClass().getName()}, this);
  }

  public void settings() {
    size(this.w, this.h, P2D);
  }

  public void setup() {
    /* pixelDensity commented out by preprocessor */;
    frameRate(30);
    surface.setLocation(0, 0);
    cp5 = new ControlP5(this);
    setupControls(this.parent, this.cp5);
  }

  public void draw() {
    background(0);
  }
}

public void setupControls(PApplet parent, ControlP5 cp5) {

  //----------------------------------------------------------------
  // Numberboxes for min and max threshold values...
  // Set by adjusting the center and width controls of the sorting threshold

  // Displays the minimum threshold value for pixel sorting
  sort_min = cp5.addNumberbox("sort_min")
    .setPosition(grid_x(8), grid_y(0))
    .setSize(size_w(3), size_h(1))
    .setDecimalPrecision(0)
    ;
  cp5.getController("sort_min").getCaptionLabel()
    .align(RIGHT, CENTER)
    .setPaddingX(5)
    ;

  sort_max = cp5.addNumberbox("sort_max")
    .setPosition(grid_x(8), grid_y(1))
    .setSize(size_w(3), size_h(1))
    .setDecimalPrecision(0)
    ;
  cp5.getController("sort_max").getCaptionLabel()
    .align(RIGHT, CENTER)
    .setPaddingX(5)
    ;

  //----------------------------------------------------------------

  cp5.addSlider("sort_c")
    .plugTo(parent, "sort_c")
    .setPosition(grid_x(0), grid_y(0))
    .setSize(size_w(8), size_h(1))
    .setRange(0, 1.0f)
    .setValue(random(1.0f))
    ;
  cp5.getController("sort_c").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;

  cp5.addSlider("sort_w")
    .plugTo(parent, "sort_w")
    .setPosition(grid_x(0), grid_y(1))
    .setSize(size_w(8), size_h(1))
    .setRange(0, 1.0f)
    .setValue(random(1.0f))
    ;
  cp5.getController("sort_w").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;

  //----------------------------------------------------------------
  // switches for processing chain

  // enable spixelsorting
  cp5.addToggle("sort")
    .plugTo(parent, "sortShader")
    .setValue(sortShader)
    .setSize(size_w(1), size_h(1))
    .setPosition(grid_x(0), grid_y(2))
    ;
  cp5.getController("sort").getCaptionLabel()
    .set("SRT")
    .align(CENTER, CENTER)
    .setPaddingX(5)
    ;

  //enable pixelshifting
  cp5.addToggle("shift")
    .plugTo(parent, "shiftShader")
    .setValue(shiftShader)
    .setSize(size_w(1), size_h(1))
    .setPosition(grid_x(1), grid_y(2))
    ;
  cp5.getController("shift").getCaptionLabel()
    .set("SHF")
    .align(CENTER, CENTER)
    .setPaddingX(5)
    ;

  //reverse the sort order
  cp5.addToggle("reverse")
    .plugTo(parent, "reverseSort")
    .setValue(reverseSort)
    .setSize(size_w(1), size_h(1))
    .setPosition(grid_x(2), grid_y(2))
    ;
  cp5.getController("reverse").getCaptionLabel()
    .set("REV")
    .align(CENTER, CENTER)
    .setPaddingX(5)
    ;

  //perform sorting and shifting before rendering of new layer on top
  cp5.addToggle("pre")
    .plugTo(parent, "preProcess")
    .setValue(preProcess)
    .setSize(size_w(1), size_h(1))
    .setPosition(grid_x(3), grid_y(2))
    ;
  cp5.getController("pre").getCaptionLabel()
    .set("PRE")
    .align(CENTER, CENTER)
    .setPaddingX(5)
    ;

  //perform sorting and shifting after rendering of new layer on top
  cp5.addToggle("post")
    .plugTo(parent, "postProcess")
    .setValue(postProcess)
    .setSize(size_w(1), size_h(1))
    .setPosition(grid_x(4), grid_y(2))
    ;
  cp5.getController("post").getCaptionLabel()
    .set("PST")
    .align(CENTER, CENTER)
    .setPaddingX(5)
    ;

  //----------------------------------------------------------------
  // selects the evaluation mode for calculating the mask used for pixel sorting

  sortModeRadio = cp5.addRadioButton("sort_mode")
    .plugTo(parent, "sort_mode")
    .setPosition(grid_x(0), grid_y(3))
    .setSize(size_w(1), size_h(1))
    .setItemsPerRow(8)
    .setSpacingColumn(buffer_h)
    .setLabelPadding(PApplet.parseInt(-0.5f*(unit_w+buffer_w)), PApplet.parseInt(-0.5f*(unit_h)))
    .addItem(">", 0)
    .addItem(">>", 1)
    .addItem("<", 2)
    .addItem("<<", 3)
    .addItem("<>", 4)
    .addItem("><", 5)
    ;

  //----------------------------------------------------------------

  cp5.addSlider("alpha_center")
    .plugTo(parent, "alphaCenter")
    .setPosition(grid_x(0), grid_y(5))
    .setSize(size_w(8), size_h(1))
    .setRange(0, 1.0f)
    .setValue(0.05f)
    ;
  cp5.getController("alpha_center").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;

  cp5.addSlider("alpha_width")
    .plugTo(parent, "alphaWidth")
    .setPosition(grid_x(0), grid_y(6))
    .setSize(size_w(8), size_h(1))
    .setRange(0, 1.0f)
    .setValue(0.15f)
    ;
  cp5.getController("alpha_width").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;

  //----------------------------------------------------------------

  cp5.addSlider("noise_zoom")
    .plugTo(parent, "noiseZoomFactor")
    .setPosition(grid_x(0), grid_y(7))
    .setSize(size_w(8), size_h(1))
    .setRange(-5.0f, 5.0f)
    .setValue(5.0f)
    ;
  cp5.getController("noise_zoom").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;

  //----------------------------------------------------------------

  cp5.addSlider("feedback_zoom")
    .plugTo(parent, "feedbackZoomFactor")
    .setPosition(grid_x(0), grid_y(8))
    .setSize(size_w(8), size_h(1))
    .setRange(0.75f, 1.25f)
    .setValue(1.125f)
    ;
  cp5.getController("feedback_zoom").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;

  cp5.addSlider("feedback_alpha")
    .plugTo(parent, "feedbackAlpha")
    .setPosition(grid_x(0), grid_y(9))
    .setSize(size_w(8), size_h(1))
    .setRange(0.0f, 1.0f)
    .setValue(0.25f)
    ;
  cp5.getController("feedback_alpha").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;

  //----------------------------------------------------------------

  cp5.addSlider("darken_amount")
    .plugTo(parent, "darkenAmount")
    .setPosition(grid_x(0), grid_y(10))
    .setSize(size_w(8), size_h(1))
    .setRange(0.0f, 1.0f)
    .setValue(0.20f)
    ;
  cp5.getController("darken_amount").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;

  cp5.addSlider("brighten_amount")
    .plugTo(parent, "brightenAmount")
    .setPosition(grid_x(0), grid_y(11))
    .setSize(size_w(8), size_h(1))
    .setRange(0.0f, 1.0f)
    .setValue(0.20f)
    ;
  cp5.getController("brighten_amount").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;

  //----------------------------------------------------------------

  cp5.addSlider("fbm_warp")
    .plugTo(parent, "fbmWarp")
    .setPosition(grid_x(0), grid_y(12))
    .setSize(size_w(8), size_h(1))
    .setRange(-5.0f, 5.0f)
    .setValue(3.25f)
    ;
  cp5.getController("fbm_warp").getCaptionLabel()
    .align(ControlP5.RIGHT, CENTER)
    ;
}

public void sort_c(float value) {
  thCenter = value;
  updateThresholds();
  sort_min.setValue(thMin);
  sort_max.setValue(thMax);
  //println("thCenter: " + thCenter + ", thWidth: " + thWidth + ", thMin: " + thMin + ", thMax: " + thMax);
}

public void sort_w(float value) {
  thWidth = value;
  updateThresholds();
  sort_min.setValue(thMin);
  sort_max.setValue(thMax);
  //println("thCenter: " + thCenter + ", thWidth: " + thWidth + ", thMin: " + thMin + ", thMax: " + thMax);
}

public void sort_mode(int mode) {
  sortMode = mode;
  sortShader = sortMode >= 0;
  //println("sortMode: " + sortMode);
}
class InputAnalyzer {
  AudioIn input;

  Amplitude amplitude;
  PitchDetector pitch;
  Waveform waveform;
  BeatDetector beat;
  FFT fft;

  int channel;
  int blockSize;
  int bands;
  float[] spectrum;

  InputAnalyzer(PApplet parent, int channel, int blockSize, int bands) {
    this.channel = channel;
    this.blockSize = blockSize;
    this.bands = bands;
    this.spectrum = new float[bands];

    try {
      this.input = new AudioIn(parent, this.channel);
      this.input.start();
    }
    catch(Exception e) {
      println("While initializing AudioIn: " + e);
      exit();
    }

    this.amplitude = new Amplitude(parent);
    this.amplitude.input(this.input);

    this.pitch = new PitchDetector(parent);
    this.pitch.input(this.input);

    this.waveform = new Waveform(parent, this.blockSize);
    this.waveform.input(this.input);

    this.beat = new BeatDetector(parent);
    this.beat.input(this.input);

    this.fft = new FFT(parent);
    this.fft.input(this.input);
  }

  public float[] getFFT() {
    this.fft.analyze(this.spectrum);
    return this.spectrum;
  }

  public Waveform getWaveform() {
    this.waveform.analyze();
    return this.waveform;
  }

  public float getAmplitude() {
    return this.amplitude.analyze();
  }

  public float getPitch() {
    return this.pitch.analyze();
  }

  public boolean isBeat() {
    return this.beat.isBeat();
  }

  public void drawWaveform(float scale, float yOffset) {
    this.waveform.analyze();
    beginShape();
    for (int i = 0; i < waveform.data.length; i++) {
      vertex(
        map(i, 0, waveform.data.length, 0, width),
        map(waveform.data[i], -1/scale, 1/scale, 0-yOffset, height-yOffset)
        );
    }
    endShape();
  }

  public void drawSpectrum() {
    this.fft.analyze(this.spectrum);
    for (int i = 0; i < this.spectrum.length; i++) {
      line(i, height, i, height - this.spectrum[i]*height*10 );
    }
  }
}
public void keyPressed() {
  switch(key) {
  case ' ':
    activePaletteA = palettes.get(PApplet.parseInt(random(palettes.size())));
    activePaletteA.randomizePastels();
    activePaletteB = palettes.get(PApplet.parseInt(random(palettes.size())));
    activePaletteB.randomizePastels();
    break;
  case 'a':
    shiftShader = !shiftShader; // toggle pixel shifting for just the shader
    break;
  case 's':
    sortShader = !sortShader; // toggle pixel sorting for just the shader
    break;
  case 'r':
    reverseSort = !reverseSort;
    break;
  case 'S':
    shiftSort = !shiftSort; // toggle pixel sorting for the feedback loop
    break;
  case 'i':
    devMode = !devMode;
    break;
  case 'm':
    sortMode ++;
    sortMode %= 8;
    break;
  case 'p':
    preProcess = !preProcess;
    break;
  case 'P':
    postProcess = !postProcess;
    break;
  }
}
//----------------------------------------------------------------
// Palettes are generated from swatches sampled from specific pastel pieces.





//================================================================

class Palette {
  String name;
  float[] background;
  float[][] pastels;

  Palette() {
    this.name = "";
    this.background = new float[]{};
    this.pastels = new float[][]{};
  }

  Palette(String _name, float[] _background, float[][] _pastels) {
    this.name = _name;
    this.background = _background;
    this.pastels = _pastels;
  }

  public Palette copy() {
    return new Palette(this.name, this.background, this.pastels);
  }

  //----------------------------------------------------------------

  public float[][] randomizePastels() {
    ArrayList<float[]> temp = new ArrayList<float[]>(this.pastels.length);
    for (int i = 0; i < this.pastels.length; i++) {
      temp.add(this.pastels[i]);
    }
    Collections.shuffle(temp);
    for (int i = 0; i < temp.size(); i++) {
      this.pastels[i] = temp.get(i);
    }
    return this.pastels;
  }

  //----------------------------------------------------------------

  public float[] getFlattenedPalette() {
    float[] flattened = new float[this.pastels.length * 4]; // 4 for RGBA
    for (int i = 0; i < this.pastels.length; i++) {
      for (int j = 0; j < this.pastels[i].length; j++) { // should iterate for RGB values
        flattened[i * 4 + j] = this.pastels[i][j];
      }
      flattened[i * 4 + 3] = 1.0f; // manually set the A to 1.0
    }
    return flattened;
  }
}

//================================================================

public ArrayList<Palette> loadPalettes() {

  ArrayList<Palette> _palettes = new ArrayList<Palette>();

  _palettes.add(new Palette(
    "473",
    new float[]{194/255.0f, 173/255.0f, 115/255.0f}, // background
    new float[][]{
      {162/255.0f, 32/255.0f, 32/255.0f}, // red
      {67/255.0f, 15/255.0f, 32/255.0f}, // dark red
      {42/255.0f, 40/255.0f, 40/255.0f}, // dark grey
      {16/255.0f, 47/255.0f, 150/255.0f}, // blue
      {234/255.0f, 232/255.0f, 229/255.0f} // white
    }));

  _palettes.add(new Palette(
    "453",
    new float[]{196/255.0f, 91/255.0f, 71/255.0f}, // background
    new float[][]{
      {196/255.0f, 91/255.0f, 71/255.0f}, // background
      {127/255.0f, 23/255.0f, 18/255.0f}, // red
      {222/255.0f, 173/255.0f, 100/255.0f}, // yellow
      {127/255.0f, 145/255.0f, 223/255.0f} // periwinkle
    }));

  _palettes.add(new Palette(
    "444",
    new float[]{203/255.0f, 197/255.0f, 185/255.0f}, // background
    new float[][]{
      {65/255.0f, 94/255.0f, 135/255.0f}, // blue
      {112/255.0f, 37/255.0f, 90/255.0f}, // violet
      {216/255.0f, 194/255.0f, 92/255.0f} // yellow
    }
    ));

  _palettes.add(new Palette(
    "443",
    new float[]{222/255.0f, 195/255.0f, 137/255.0f}, // background
    new float[][]{
      {131/255.0f, 51/255.0f, 113/255.0f}, // violet
      {147/255.0f, 28/255.0f, 18/255.0f}, // red
      {220/255.0f, 167/255.0f, 57/255.0f}, // yellow
      {85/255.0f, 113/255.0f, 132/255.0f}, // light blue
      {170/255.0f, 189/255.0f, 154/255.0f} // aqua
    }));

  _palettes.add(new Palette(
    "441",
    new float[]{234/255.0f, 209/255.0f, 155/255.0f}, // background
    new float[][]{
      {196/255.0f, 121/255.0f, 87/255.0f}, // red
      {86/255.0f, 111/255.0f, 134/255.0f}, // blue
      {239/255.0f, 234/255.0f, 232/255.0f} // white
    }));

  _palettes.add(new Palette(
    "180",
    new float[]{149/255.0f, 118/255.0f, 145/255.0f}, // background
    new float[][]{
      {36/255.0f, 34/255.0f, 33/255.0f}, // dark grey
      {134/255.0f, 25/255.0f, 37/255.0f}, // red
      {178/255.0f, 41/255.0f, 25/255.0f}, // orange
      {59/255.0f, 67/255.0f, 61/255.0f} // green
    }));

  _palettes.add(new Palette(
    "178",
    new float[]{103/255.0f, 116/255.0f, 146/255.0f}, // background
    new float[][]{
      {37/255.0f, 36/255.0f, 37/255.0f}, // dark grey
      {101/255.0f, 16/255.0f, 29/255.0f}, // maroon
      {162/255.0f, 54/255.0f, 25/255.0f}, // orange
      {218/255.0f, 204/255.0f, 95/255.0f}, // yellow
      {222/255.0f, 222/255.0f, 220/255.0f}, // white
      {31/255.0f, 73/255.0f, 155/255.0f} // blue
    }));

  _palettes.add(new Palette(
    "177",
    new float[]{70/255.0f, 64/255.0f, 68/255.0f}, // background
    new float[][]{
      {26/255.0f, 64/255.0f, 160/255.0f}, // blue
      {153/255.0f, 58/255.0f, 25/255.0f}, // orange
      {237/255.0f, 222/255.0f, 125/255.0f}, // yellow
      {226/255.0f, 225/255.0f, 223/255.0f} // white
    }));

  _palettes.add(new Palette(
    "176",
    new float[]{178/255.0f, 57/255.0f, 83/255.0f}, // background
    new float[][]{
      {24/255.0f, 63/255.0f, 164/255.0f}, // blue
      {176/255.0f, 36/255.0f, 25/255.0f}, // red
      {206/255.0f, 167/255.0f, 79/255.0f}, // yellow
      {31/255.0f, 29/255.0f, 29/255.0f} // dark grey
    }));

  _palettes.add(new Palette(
    "161",
    new float[]{187/255.0f, 93/255.0f, 81/255.0f}, // background
    new float[][]{
      {31/255.0f, 76/255.0f, 182/255.0f}, // blue
      {194/255.0f, 60/255.0f, 30/255.0f}, // red
      {229/255.0f, 229/255.0f, 235/255.0f}, // white
      {39/255.0f, 35/255.0f, 35/255.0f} // dark grey
    }));

  _palettes.add(new Palette(
    "273",
    new float[]{150/255.0f, 162/255.0f, 186/255.0f}, // background
    new float[][]{
      {32/255.0f, 67/255.0f, 196/255.0f}, // blue
      {171/255.0f, 62/255.0f, 33/255.0f}, // orange
      {230/255.0f, 212/255.0f, 123/255.0f} // yellow
    }));

  _palettes.add(new Palette(
    "256",
    new float[]{183/255.0f, 95/255.0f, 66/255.0f}, // background
    new float[][]{
      {228/255.0f, 225/255.0f, 223/255.0f}, // white
      {100/255.0f, 75/255.0f, 125/255.0f}, // violet
      {155/255.0f, 37/255.0f, 20/255.0f}, // red
      {112/255.0f, 19/255.0f, 15/255.0f} // dark red
    }));

  _palettes.add(new Palette(
    "151",
    new float[]{61/255.0f, 60/255.0f, 58/255.0f}, // background
    new float[][]{
      {25/255.0f, 65/255.0f, 167/255.0f}, // blue
      {125/255.0f, 53/255.0f, 21/255.0f}, // orange
      {86/255.0f, 12/255.0f, 19/255.0f}, // red
      {239/255.0f, 238/255.0f, 237/255.0f} // white
    }));

  _palettes.add(new Palette(
    "120",
    new float[]{61/255.0f, 60/255.0f, 58/255.0f}, // background
    new float[][]{
      {25/255.0f, 65/255.0f, 167/255.0f}, // violet
      {125/255.0f, 53/255.0f, 21/255.0f}, // orange
      {86/255.0f, 12/255.0f, 19/255.0f}, // black
      {239/255.0f, 238/255.0f, 237/255.0f} // white
    }));

  _palettes.add(new Palette(
    "119",
    new float[]{200/255.0f, 150/255.0f, 154/255.0f}, // background
    new float[][]{
      {161/255.0f, 92/255.0f, 58/255.0f}, // brown
      {173/255.0f, 51/255.0f, 25/255.0f}, // orange
      {212/255.0f, 168/255.0f, 82/255.0f}, // yellow
      {221/255.0f, 214/255.0f, 205/255.0f}, // white
      {128/255.0f, 105/255.0f, 160/255.0f}, // violet
      {21/255.0f, 52/255.0f, 140/255.0f}, // blue
      {42/255.0f, 39/255.0f, 41/255.0f} // black
    }));

  _palettes.add(new Palette(
    "339",
    new float[]{146/255.0f, 36/255.0f, 68/255.0f}, // background
    new float[][]{
      {170/255.0f, 34/255.0f, 23/255.0f}, // red
      {38/255.0f, 36/255.0f, 39/255.0f}, // black
      {63/255.0f, 65/255.0f, 79/255.0f} // grey
    }));

  _palettes.add(new Palette(
    "332",
    new float[]{197/255.0f, 187/255.0f, 166/255.0f}, // background
    new float[][]{
      {225/255.0f, 208/255.0f, 91/255.0f}, // yellow
      {36/255.0f, 36/255.0f, 40/255.0f}, // black
      {24/255.0f, 63/255.0f, 159/255.0f}, // blue
      {229/255.0f, 228/255.0f, 228/255.0f} // white
    }));

  _palettes.add(new Palette(
    "332",
    new float[]{142/255.0f, 146/255.0f, 140/255.0f}, // background
    new float[][]{
      {115/255.0f, 20/255.0f, 30/255.0f}, // red
      {142/255.0f, 40/255.0f, 20/255.0f}, // orange
      {30/255.0f, 75/255.0f, 177/255.0f}, // blue
    }));

  return _palettes;
}


  public void settings() { fullScreen(P2D, 2);
pixelDensity(1); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--hide-stop", "Interactive" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
